version: '2'

volumes:
  data:

services:

  docs:
    # update gh-pages => git subtree push --prefix docs/phi origin gh-pages
    build: .
    volumes:
      - ./:/phi
    working_dir: /phi
    command: ./gen_docs

  test:
    build: .
    volumes:
      - ./:/phi
    working_dir: /phi
    command: py.test
